import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import Product from "~/components/Product";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>FeiraOnline</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start">
        <Header />
        <div className="grid grid-cols-3 gap-2 p-4 md:grid-cols-6 md:gap-4 md:p-8">
          {[
            {
              name: "Couve",
              price: "0.99€/kg",
              producer: "Leiria",
              img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
            },
            {
              name: "Couve",
              price: "0.99€/kg",
              producer: "Leiria",
              img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
            },
            {
              name: "Couve",
              price: "0.99€/kg",
              producer: "Leiria",
              img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
            },
            {
              name: "Couve",
              price: "0.99€/kg",
              producer: "Leiria",
              img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
            },
            {
              name: "Couve",
              price: "0.99€/kg",
              producer: "Leiria",
              img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
            },
            {
              name: "Couve",
              price: "0.99€/kg",
              producer: "Leiria",
              img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
            },
            {
              name: "Couve",
              price: "0.99€/kg",
              producer: "Leiria",
              img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
            },
          ].map((p) => (
            <Product {...p} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
