export const mock = [
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
];
