export const mock = [
  {
    name: "Couve Brócolo",
    price: "2.99€/kg",
    alternativePrice: "1.32€/un",
    producer: "Leiria",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwb527b076/images/col/207/2076764-frente.jpg",
  },
  {
    name: "Couve Flor Inteira",
    price: "2.69€/kg",
    alternativePrice: "3.77€/un",
    producer: "Aveiro",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw2ef44391/images/col/207/2076768-cima.jpg?",
  },
  {
    name: "Couve Coração Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.19€/un",
    producer: "Lisboa",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw0ea229c4/images/col/207/2076767-frente.jpg?sw=280&sh=280",
  },
  {
    name: "Couve Lombarda/Saboia Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.59€/un",
    producer: "Algarve",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwe328a8bb/images/col/207/2076771-direito.jpg?sw=280&sh=280",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve Brócolo",
    price: "2.99€/kg",
    alternativePrice: "1.32€/un",
    producer: "Leiria",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwb527b076/images/col/207/2076764-frente.jpg",
  },
  {
    name: "Couve Flor Inteira",
    price: "2.69€/kg",
    alternativePrice: "3.77€/un",
    producer: "Aveiro",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw2ef44391/images/col/207/2076768-cima.jpg?",
  },
  {
    name: "Couve Coração Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.19€/un",
    producer: "Lisboa",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw0ea229c4/images/col/207/2076767-frente.jpg?sw=280&sh=280",
  },
  {
    name: "Couve Lombarda/Saboia Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.59€/un",
    producer: "Algarve",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwe328a8bb/images/col/207/2076771-direito.jpg?sw=280&sh=280",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve Brócolo",
    price: "2.99€/kg",
    alternativePrice: "1.32€/un",
    producer: "Leiria",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwb527b076/images/col/207/2076764-frente.jpg",
  },
  {
    name: "Couve Flor Inteira",
    price: "2.69€/kg",
    alternativePrice: "3.77€/un",
    producer: "Aveiro",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw2ef44391/images/col/207/2076768-cima.jpg?",
  },
  {
    name: "Couve Coração Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.19€/un",
    producer: "Lisboa",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw0ea229c4/images/col/207/2076767-frente.jpg?sw=280&sh=280",
  },
  {
    name: "Couve Lombarda/Saboia Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.59€/un",
    producer: "Algarve",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwe328a8bb/images/col/207/2076771-direito.jpg?sw=280&sh=280",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve Brócolo",
    price: "2.99€/kg",
    alternativePrice: "1.32€/un",
    producer: "Leiria",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwb527b076/images/col/207/2076764-frente.jpg",
  },
  {
    name: "Couve Flor Inteira",
    price: "2.69€/kg",
    alternativePrice: "3.77€/un",
    producer: "Aveiro",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw2ef44391/images/col/207/2076768-cima.jpg?",
  },
  {
    name: "Couve Coração Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.19€/un",
    producer: "Lisboa",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw0ea229c4/images/col/207/2076767-frente.jpg?sw=280&sh=280",
  },
  {
    name: "Couve Lombarda/Saboia Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.59€/un",
    producer: "Algarve",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwe328a8bb/images/col/207/2076771-direito.jpg?sw=280&sh=280",
  },
  {
    name: "Couve",
    price: "0.99€/kg",
    producer: "Leiria",
    img: "https://www.freshpoint.com/wp-content/uploads/2020/02/Freshpoint-green-cabbage.jpg",
  },
  {
    name: "Couve Brócolo",
    price: "2.99€/kg",
    alternativePrice: "1.32€/un",
    producer: "Leiria",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwb527b076/images/col/207/2076764-frente.jpg",
  },
  {
    name: "Couve Flor Inteira",
    price: "2.69€/kg",
    alternativePrice: "3.77€/un",
    producer: "Aveiro",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw2ef44391/images/col/207/2076768-cima.jpg?",
  },
  {
    name: "Couve Coração Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.19€/un",
    producer: "Lisboa",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw0ea229c4/images/col/207/2076767-frente.jpg?sw=280&sh=280",
  },
  {
    name: "Couve Lombarda/Saboia Inteira",
    price: "1.99€/kg",
    alternativePrice: "2.59€/un",
    producer: "Algarve",
    img: "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwe328a8bb/images/col/207/2076771-direito.jpg?sw=280&sh=280",
  },
];
